### ISSUE TITLE
Product Roadmap

### ISSUE THREAD

**Issue by bsmithgall** [codeforamerica/lunch-club#1]
- [ ] View the club with slack command
- [ ] Logic for the actual lunch start time
  - [ ] Random time between 12-1 to start
  - [ ] Allow people to post times
- [ ] Slack notifications: #lunch-club channel and slackbot for signed-up members
- [ ] Configure domains
- [ ] Audio notifications over rpi
- [ ] Integration with Roulette?
